# The URL the site will be built for
base_url = "https://sthiele.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Which theme to use for the code highlighting.
highlight_theme = "gruvbox-light"
# "base16-ocean-dark"

insert_anchor_links = "left"

generate_rss = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# theme = "even"
# theme = "hyde"

taxonomies = [
    {name = "tags", rss = true},
]

[extra]
# Put all your custom variables here

author = "Sven Thiele"
# even_title = "sthiele"
even_title = "sthiele weblog"

# This is the default menu
even_menu = [
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/publications", name = "Publications"},
    {url = "$BASE_URL/software", name = "Software"},
    {url = "$BASE_URL/about", name = "About"},
]

# hyde_theme = "theme-base-0d"
# hyde_links = [
#     {url = "/", name = "Home"},
#     {url = "/tags", name = "Tags"},
#     {url = "/publications", name = "Publications"},
#     {url = "/software", name = "Software"},
#     {url = "/about", name = "About"},
# ]
